/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestion_maintenance;

import java.awt.HeadlessException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class NouveauTechnicien extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NouveauTechnicien.class.getName());

    /**
     * Creates new form NouveauTechnicien
     */
     private int userId;
     private String technicien, mdp;
     
    public NouveauTechnicien(int userId) {
        initComponents();
        setTitle("MaintFlow - Ajouter un nouveau technicien");
        this.userId = userId;
    }

    private NouveauTechnicien() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titre = new javax.swing.JLabel();
        inumtel = new javax.swing.JTextField();
        itechnicien = new javax.swing.JTextField();
        imdp = new javax.swing.JTextField();
        icomp = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        javax.swing.JButton valider = new javax.swing.JButton();
        javax.swing.JButton annuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        titre.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        titre.setForeground(new java.awt.Color(0, 153, 153));
        titre.setText("AJOUTER UN NOUVEAU TECHNICIEN");

        inumtel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inumtel.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        itechnicien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itechnicien.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        itechnicien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itechnicienActionPerformed(evt);
            }
        });

        imdp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        imdp.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        icomp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        icomp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mécanique", "Eléctrique", "Pneumatique", "Soudure", "Hydraulique" }));
        icomp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                icompActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel2.setText("Technicien :");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel3.setText("Numéro Téléphone :");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel4.setText("Mot de passe :");

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel7.setText("Compétences :");

        valider.setBackground(new java.awt.Color(0, 153, 153));
        valider.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        valider.setForeground(new java.awt.Color(255, 255, 255));
        valider.setText("Enregistrer");
        valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerActionPerformed(evt);
            }
        });

        annuler.setBackground(new java.awt.Color(255, 153, 51));
        annuler.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        annuler.setForeground(new java.awt.Color(255, 255, 255));
        annuler.setText("Annuler");
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(titre))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))
                                .addGap(127, 127, 127))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(valider, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(itechnicien)
                            .addComponent(imdp)
                            .addComponent(inumtel)
                            .addComponent(icomp, 0, 243, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(titre, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itechnicien, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inumtel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imdp, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(icomp, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valider, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        icomp.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itechnicienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itechnicienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itechnicienActionPerformed

    private void validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerActionPerformed
        technicien = itechnicien.getText();
        String numtel = inumtel.getText();
        mdp = imdp.getText();
        String comp = (String)icomp.getSelectedItem();

        if (mdp.isEmpty()||technicien.isEmpty()||numtel.isEmpty()){
            JOptionPane.showMessageDialog(this, 
                "Veuillez remplir tous les champs",
                "Erreur de validation", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!numtel.matches("\\d{8}")) {
            JOptionPane.showMessageDialog(this, 
                "Le numéro de téléphone doit contenir exactement 8 chiffres",
                "Erreur de validation", 
                JOptionPane.ERROR_MESSAGE);
            inumtel.requestFocus();
            return;
        }

        Connection conn = null;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/users";
            String username_db = "root";
            String password_db = "";

            conn = DriverManager.getConnection(url, username_db, password_db);
            conn.setAutoCommit(false); // Start transaction

            // 1. Insert technician
            try (PreparedStatement pstmt = conn.prepareStatement(
                 "INSERT INTO techniciens (technicien, telephone, mdp, competences, id_user) VALUES (?, ?, ?, ?, ?)",
                 PreparedStatement.RETURN_GENERATED_KEYS)) {

                pstmt.setString(1, technicien);
                pstmt.setString(2, numtel);
                pstmt.setString(3, mdp);
                pstmt.setString(4, comp);
                pstmt.setInt(5, userId);

                int rowsAffected = pstmt.executeUpdate();

                if (rowsAffected > 0) {
                    // 2. Get the auto-generated ID
                    try (ResultSet rs = pstmt.getGeneratedKeys()) {
                        if (rs.next()) {
                            int id = rs.getInt(1);

                            // 3. Create login account
                            try (PreparedStatement loginStmt = conn.prepareStatement(
                                "INSERT INTO login (id_user, username, password, type) VALUES (?, ?, ?, ?)")) {

                                loginStmt.setInt(1, id);
                                loginStmt.setString(2, technicien);
                                loginStmt.setString(3, mdp);
                                loginStmt.setString(4, "technicien");

                                loginStmt.executeUpdate();
                                conn.commit(); // Commit transaction

                                JOptionPane.showMessageDialog(this, 
                                    "Technicien et compte créés avec succès!",
                                    "Succès", 
                                    JOptionPane.INFORMATION_MESSAGE);

                                new Techniciens(userId).setVisible(true);
                                this.dispose();
                            } catch (IOException ex) {
                                System.getLogger(NouveauTechnicien.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                            }
                        }
                    }
                } else {
                    conn.rollback();
                    JOptionPane.showMessageDialog(this, 
                        "L'ajout du technicien a échoué",
                        "Erreur", 
                        JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (ClassNotFoundException ex) {
            try { if (conn != null) conn.rollback(); } catch (SQLException e) {}
            JOptionPane.showMessageDialog(this, 
                "Driver JDBC MySQL introuvable",
                "Erreur", 
                JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            try { if (conn != null) conn.rollback(); } catch (SQLException e) {}
            JOptionPane.showMessageDialog(this, 
                "Erreur de base de données: " + ex.getMessage(),
                "Erreur", 
                JOptionPane.ERROR_MESSAGE);
        } finally {
            try { if (conn != null) conn.setAutoCommit(true); } catch (SQLException e) {}
            try { if (conn != null) conn.close(); } catch (SQLException e) {}
        }
    }//GEN-LAST:event_validerActionPerformed

    private void icompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_icompActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_icompActionPerformed

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
        try {
            new Techniciens(userId).setVisible(true);
        } catch (SQLException | IOException ex) {
            System.getLogger(NouveauTechnicien.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_annulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NouveauTechnicien().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> icomp;
    private javax.swing.JTextField imdp;
    private javax.swing.JTextField inumtel;
    private javax.swing.JTextField itechnicien;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables

    private void creer_compte(int id) {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/users";
            String username_db = "root";
            String password_db = "";

            try (Connection conn = DriverManager.getConnection(url, username_db, password_db);
                 PreparedStatement pstmt = conn.prepareStatement("INSERT INTO login (id_user, username, password, type) VALUES (?, ?, ?, ?)")) {
                pstmt.setInt(1, id);
                 pstmt.setString(2, technicien);
                 pstmt.setString(3, mdp);
                 pstmt.setString(4, "technicien");
                 pstmt.executeUpdate();
            }
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println("erreur !");
        }
    }
}
