/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestion_maintenance;

import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class UpdateDI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UpdateDI.class.getName());

    /**
     * Creates new form UpdateDI
     */
     private int userId;
     private int id;
     private String numImm;
     private String operation;
     private Date sqlDate;
     
    public UpdateDI(int userId, int id_intervention, String numImm, 
               String description, Date date, String heure, String technicien, String statut) {
        initComponents();
        setTitle("MaintFlow - Détails d'une demande d'intervention");
        this.id = id_intervention;
        this.numImm = numImm;
        this.userId = userId;
        loadTechniciens();
        idescription.setText(description);
        idate.setDate(date);
        iheure.setText(heure);
        selectComboItem(inumImm, numImm);
        selectComboItem(itechnicien, technicien);
        istatut.setSelectedItem(statut);
        this.operation = description ;
        this.setTitle("Détails de la demande d'intervention.");
    }

    // Méthode utilitaire pour sélectionner un item dans un JComboBox
    private void selectComboItem(JComboBox<String> combo, String value) {
        for (int i = 0; i < combo.getItemCount(); i++) {
            if (combo.getItemAt(i).equals(value)) {
                combo.setSelectedIndex(i);
                return;
            }
        }
        combo.addItem(value);
        combo.setSelectedItem(value);
    }

    private UpdateDI() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    private void loadTechniciens() {
        try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/users", "root", "");
             PreparedStatement pst = conn.prepareStatement("SELECT technicien FROM techniciens WHERE id_user = ?")) {

            pst.setInt(1, userId);
            ResultSet rs = pst.executeQuery();

            itechnicien.removeAllItems();

            while (rs.next()) {
                String nomTech = rs.getString("technicien");
                itechnicien.addItem(nomTech);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, 
                "Erreur lors du chargement des techniciens : " + e.getMessage());
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titre = new javax.swing.JLabel();
        javax.swing.JButton valider = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        idate = new com.toedter.calendar.JCalendar();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        iheure = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        itechnicien = new javax.swing.JComboBox<>();
        istatut = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        javax.swing.JButton supprimer = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        inumImm = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        idescription = new javax.swing.JTextArea();
        javax.swing.JButton terminer = new javax.swing.JButton();
        javax.swing.JButton annuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        titre.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        titre.setForeground(new java.awt.Color(0, 153, 153));
        titre.setText("DEMANDE D'INTERVENTION");

        valider.setBackground(new java.awt.Color(0, 153, 153));
        valider.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        valider.setForeground(new java.awt.Color(255, 255, 255));
        valider.setText("Enregistrer");
        valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Description :");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Date :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Heure :");

        iheure.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        iheure.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        iheure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iheureActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Technicien : ");

        istatut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        istatut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "En attente", "En réparation" }));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Statut :");

        supprimer.setBackground(new java.awt.Color(255, 51, 51));
        supprimer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        supprimer.setForeground(new java.awt.Color(255, 255, 255));
        supprimer.setText("Supprimer");
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Num° Imm :");

        inumImm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        idescription.setColumns(20);
        idescription.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        idescription.setRows(5);
        jScrollPane2.setViewportView(idescription);

        terminer.setBackground(new java.awt.Color(0, 153, 0));
        terminer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        terminer.setForeground(new java.awt.Color(255, 255, 255));
        terminer.setText("Marquer comme terminé");
        terminer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminerActionPerformed(evt);
            }
        });

        annuler.setBackground(new java.awt.Color(255, 153, 51));
        annuler.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        annuler.setForeground(new java.awt.Color(255, 255, 255));
        annuler.setText("Annuler");
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(idate, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 22, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inumImm, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(itechnicien, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(35, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(iheure, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(istatut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(valider, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(titre)
                        .addGap(204, 204, 204))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(terminer, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(329, 329, 329))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(titre, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(itechnicien, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iheure, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idate, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inumImm, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(istatut, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 109, Short.MAX_VALUE)))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valider, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(terminer, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerActionPerformed
        String description = idescription.getText();
        String numImm = (String) inumImm.getSelectedItem();
        Date date = idate.getDate();
        this.sqlDate = new java.sql.Date(date.getTime());
        String heure = iheure.getText();
        String technicien = (String) itechnicien.getSelectedItem();
        String statut = (String) istatut.getSelectedItem();
        
        if (description.isEmpty()|| heure.isEmpty() ||technicien.isEmpty()){
            JOptionPane.showMessageDialog(this, 
                "Veuillez remplir tous les champs",
                "Erreur de validation", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/users", "root", "");
             PreparedStatement pstmt = conn.prepareStatement("UPDATE interventions SET description = ?, date = ?, heure = ?, statut = ?, technicien = ?, NumImm = ? ,id_user = ? ")) {

            pstmt.setString(1, description);
            pstmt.setDate(2, (java.sql.Date) sqlDate);
            pstmt.setString(3, heure);
            pstmt.setString(4, statut);
            pstmt.setString(5, technicien);
            pstmt.setString(6, numImm);
            pstmt.setInt(7, userId);

            int rowsAffected = pstmt.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "DI ajouté avec succès!");

                this.dispose();
                Intervention fr = new Intervention(userId);
                fr.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "L'ajout a échoué", "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Erreur de base de données: " + e.getMessage(), 
                "Erreur", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_validerActionPerformed

    private void iheureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iheureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iheureActionPerformed

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        try (Connection conn = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/users", "root", "");
        PreparedStatement pstmt = conn.prepareStatement(
            "DELETE FROM interventions WHERE id_intervention=?")) {

        pstmt.setInt(1, this.id);

        int rowsAffected = pstmt.executeUpdate();

        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(this,
                "DI supprimé avec succès!",
                "Succès", JOptionPane.INFORMATION_MESSAGE);
            this.dispose(); // Close the window after successful update
        } else {
            JOptionPane.showMessageDialog(this,
                "Aucun DI trouvé avec cet ID",
                "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        this.dispose();
        Intervention fr = new Intervention(userId);
        fr.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                "Erreur de base de données: " + ex.getMessage(),
                "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_supprimerActionPerformed

    private void terminerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminerActionPerformed
        try (Connection conn = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/users", "root", "")) {

            java.util.Date utilDate = idate.getDate();
            java.sql.Date sqlDate1 = new java.sql.Date(utilDate.getTime());

            // 3. Mettre à jour l'intervention
            try (PreparedStatement pstmt = conn.prepareStatement(
                "UPDATE interventions SET statut = ? WHERE NumImm = ? AND id_user = ?")) {

                pstmt.setString(1, "Terminée");
                pstmt.setString(2, numImm);
                pstmt.setInt(3, userId);
                pstmt.executeUpdate();
            }

            // 4. Mettre à jour le véhicule
            try (PreparedStatement pstmt2 = conn.prepareStatement(
                "UPDATE vehicules SET statut = ? WHERE NumImm = ? and id_user = ?")) {

                pstmt2.setInt(1, 0);
                pstmt2.setString(1, "Actif");
                pstmt2.setString(2, numImm);
                pstmt2.setInt(3, userId);
                pstmt2.executeUpdate();
            }

            // 5. Insérer dans archive
            try (PreparedStatement pstmt3 = conn.prepareStatement(
                "INSERT INTO archive (NumImm, date_maintenance, operation, id_user) VALUES (?, ?, ?, ?)")) {

                pstmt3.setString(1, numImm);
                pstmt3.setDate(2, sqlDate1);
                pstmt3.setString(3, operation);
                pstmt3.setInt(4, userId);
                pstmt3.executeUpdate();
            }

            // 6. Supprimer l'intervention
            try (PreparedStatement pstmt4 = conn.prepareStatement(
                "DELETE FROM interventions WHERE numImm = ? and id_user = ?")) {

                pstmt4.setString(1, numImm);
                pstmt4.setInt(2, userId);
                pstmt4.executeUpdate();
            }

            JOptionPane.showMessageDialog(this,
                "Opération terminée avec succès!",
                "Succès", JOptionPane.INFORMATION_MESSAGE);

            new Intervention(userId).setVisible(true);
            this.dispose();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                "Erreur de base de données: " + ex.getMessage(),
                "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_terminerActionPerformed

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
        try {
            new Intervention(userId).setVisible(true);
            this.dispose();
        } catch (SQLException | IOException ex) {
            System.getLogger(UpdateDI.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }//GEN-LAST:event_annulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UpdateDI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar idate;
    private javax.swing.JTextArea idescription;
    private javax.swing.JTextField iheure;
    private javax.swing.JComboBox<String> inumImm;
    private javax.swing.JComboBox<String> istatut;
    private javax.swing.JComboBox<String> itechnicien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables
}
